server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: chat-realtime-backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5433/dbmoji
    username: postgres
    password: "@Abc123456"
    driver-class-name: org.postgresql.Driver

jwt:
  access-token-key: ${ACCESS_TOKEN:dbVkYCHQIBx33giGxnJic7noT0eagNcR}
  refresh-token-key: ${REFRESH_TOKEN:Wu8w4pkiVmErS9Z9Loel7tMBM7f3VFjD}
  access-token-duration: ${ACCESS_TOKEN_DURATION:540} # in second
  refresh-token-duration: ${REFRESH_TOKEN:3600} # in second

open:
  api:
    title: API Moji document
    version: v1.0.0
    description: Moji API description
    serverUrl: http://localhost:8080
    serverName: Server Test